spring:
  application:
    name: vaguinhasdev-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vaguinhasdev}
    username: ${DATABASE_USERNAME:vaguinhasdev}
    password: ${DATABASE_PASSWORD:vaguinhasdev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
